### ISSUE TITLE
pip installer has old version of pdf-link-checker

### ISSUE THREAD

**Issue by karplus** [bootlin/pdf-link-checker#4]
The pip installer seems to be set up for a much older version of pdf-link-checker—one that has syntax errors for Python 3.

**Comment by ksilz** [comment]
Here's what I get running `pdf-link-checker` on the Mac with Python 3.9:

```
  File "/usr/local/bin/pdf-link-checker", line 105
    except urllib2.HTTPError, why:
                            ^
SyntaxError: invalid syntax
```

**Comment by prof-rice** [comment]
> Here's what I get running `pdf-link-checker` on the Mac with Python 3.9:
> 
> ```
>   File "/usr/local/bin/pdf-link-checker", line 105
>     except urllib2.HTTPError, why:
>                             ^
> SyntaxError: invalid syntax
> ```

I get the same error on Ubuntu Linux with Python 3.9.5.

**Comment by yegorich** [comment]
@michaelopdenacker could you take a look at #7 and make a new release?

**Comment by michaelopdenacker** [comment]
Done.
Closing the bug as we don't use urllib2 any more.

**Comment by arkivm** [comment]
Do you intend to make a new release on pypi? [I still see v1.1.1](https://pypi.org/project/pdf-link-checker/)
